# Generated by Django 4.2.7 on 2025-11-23 13:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('upvotes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvotes_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InnovationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='innovations.innovation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('innovation', 'user')},
            },
        ),
    ]
