version: "3.9"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: intranet-backend
    env_file: .env
    command: >
      sh -c "
      python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.settings_production
      - DATABASE_URL=postgresql://intranetuser:intranetpass@db:5432/intranetdb
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_DB=intranetdb
      - POSTGRES_USER=intranetuser
      - POSTGRES_PASSWORD=intranetpass
      - POSTGRES_HOST=db
      - NGROK_AUTH_TOKEN=328yKQblyTdYYT8nvHiOLLjIplu_2N6NpqMXV7iV6dWiDVFNc
  
    volumes:
      - ./back-end:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_AUTH0_DOMAIN=dev-2685h5q7efjt6peh.us.auth0.com
        - VITE_AUTH0_CLIENT_ID=GjkjPfZrtR4XAv820vmde7SDlGeUnkwJ
        - VITE_AUTH0_AUDIENCE=https://intranet/api
    container_name: intranet-frontend
    ports:
      - "8080:80"   
    depends_on:
      - backend

  
  db:
    image: postgres:15.7
    container_name: intranet-db
    restart: always
    environment:
      POSTGRES_DB: intranetdb
      POSTGRES_USER: intranetuser
      POSTGRES_PASSWORD: intranetpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intranetuser -d intranetdb"]
      interval: 10s
      timeout: 5s
      retries: 5


      
  redis:
    image: redis:7-alpine
    container_name: intranet-redis
    # Expose only within the Docker network; no host port binding needed

volumes:
  postgres_data:
