import React from "react";

/**
 * Avatar component that displays a user's profile picture or autogenerated initials.
 * 
 * @param {string} src - URL of the profile picture
 * @param {string} name - Name of the user (for initials and color generation)
 * @param {number} size - Size in pixels (width and height)
 * @param {object} style - Additional styles
 */
const Avatar = ({ src, name, size = 40, style = {} }) => {
  const [imgError, setImgError] = React.useState(false);

  const initials = name
    ? name
        .split(" ")
        .map((n) => n[0])
        .join("")
        .substring(0, 2)
        .toUpperCase()
    : "?";

  // Generate a consistent color based on the name
  const getColor = (str) => {
    if (!str) return "#1B467A";
    const colors = [
      "#1B467A", "#2c3e50", "#8e44ad", "#2980b9", "#27ae60",
      "#16a085", "#f39c12", "#d35400", "#c0392b", "#34495e"
    ];
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    const index = Math.abs(hash) % colors.length;
    return colors[index];
  };

  const containerStyle = {
    width: size,
    height: size,
    borderRadius: "50%",
    backgroundColor: getColor(name),
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: `${size * 0.4}px`,
    userSelect: "none",
    overflow: "hidden",
    flexShrink: 0,
    border: "2px solid #fff",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    ...style,
  };

  if (src && !imgError) {
    return (
      <img
        src={src}
        alt={name}
        style={{
          ...containerStyle,
          objectFit: "cover",
        }}
        onError={() => setImgError(true)}
      />
    );
  }

  return (
    <div style={containerStyle} title={name}>
      {initials}
    </div>
  );
};

export default Avatar;
