# Generated by Django 5.2.3 on 2025-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('it', 'IT'), ('finance', 'Finance'), ('marketing', 'Marketing')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('employee', 'Employee'), ('manager', 'Manager')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('kitro', 'Kitro Team (AI/ML)'), ('devops', 'DevOps'), ('support', 'IT Support')], max_length=50, null=True),
        ),
    ]
